/**
 * Type definitions for ActionsSetupPython5
 * 
 * Generated from action.yml
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * @see {@link https://github.com/actions/setup-python GitHub Repository}
 */

export interface ActionsSetupPython5Inputs {
  "python-version"?: string;
  "python-version-file"?: string;
  cache?: string;
  architecture?: string;
  "check-latest"?: boolean;
  token?: string;
  "cache-dependency-path"?: string;
  "update-environment"?: boolean;
  "allow-prereleases"?: boolean;
  freethreaded?: boolean;
}

export interface ActionsSetupPython5Outputs {
  "python-version": string;
  "cache-hit": string;
  "python-path": string;
}

export interface ActionsSetupPython5Metadata {
  inputs: ActionsSetupPython5Inputs;
  outputs: ActionsSetupPython5Outputs;
}

/**
 * Action class for actions/setup-python@v5
 * 
 * This class represents the imported action and provides type-safe access
 * to the action reference string.
 * 
 * This is a static class - use the class directly, no instantiation needed.
 * Example: step.uses(ActionsSetupPython5)
 * 
 * @see {@link https://github.com/actions/setup-python GitHub Repository}
 */
class ActionsSetupPython5Impl {
  /**
   * The action reference string (e.g., "actions/checkout@v4")
   * This is a static property - access it via the class: ActionsSetupPython5.reference
   */
  static readonly reference: string = "actions/setup-python@v5";
  
  /**
   * Private constructor to prevent instantiation
   * Use the class directly as a static reference
   */
  private constructor() {}
}

// Export the class with the reference property on the constructor
// This allows TypeScript to recognize the reference property on the class itself
// Use 'as const' assertion to preserve the literal type of the reference string
/**
 * Action class for actions/setup-python@v5
 * 
 * This class represents the imported action and provides type-safe access
 * to the action reference string.
 * 
 * This is a static class - use the class directly, no instantiation needed.
 * Example: step.uses(ActionsSetupPython5)
 * 
 * @see {@link https://github.com/actions/setup-python GitHub Repository}
 */
export const ActionsSetupPython5 = ActionsSetupPython5Impl as typeof ActionsSetupPython5Impl & { readonly reference: "actions/setup-python@v5" };

// Add reference property to the exported class for runtime access
Object.defineProperty(ActionsSetupPython5, "reference", {
  value: "actions/setup-python@v5",
  writable: false,
  enumerable: true,
  configurable: false,
});
