/**
 * Type definitions for ActionsSetupNode4
 *
 * Generated from action.yml
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * @see {@link https://github.com/actions/setup-node GitHub Repository}
 */

export interface ActionsSetupNode4Inputs {
  "always-auth"?: string;
  "node-version"?: string;
  "node-version-file"?: string;
  architecture?: string;
  "check-latest"?: boolean;
  "registry-url"?: string;
  scope?: string;
  token?: string;
  cache?: string;
  "cache-dependency-path"?: string;
  mirror?: string;
  "mirror-token"?: string;
}

export interface ActionsSetupNode4Outputs {
  "cache-hit": string;
  "node-version": string;
}

export interface ActionsSetupNode4Metadata {
  inputs: ActionsSetupNode4Inputs;
  outputs: ActionsSetupNode4Outputs;
}

/**
 * Action class for actions/setup-node@v4
 *
 * This class represents the imported action and provides type-safe access
 * to the action reference string.
 *
 * This is a static class - use the class directly, no instantiation needed.
 * Example: step.uses(ActionsSetupNode4)
 *
 * @see {@link https://github.com/actions/setup-node GitHub Repository}
 */
class ActionsSetupNode4Impl {
  /**
   * The action reference string (e.g., "actions/checkout@v4")
   * This is a static property - access it via the class: ActionsSetupNode4.reference
   */
  static readonly reference: string = "actions/setup-node@v4";

  /**
   * Private constructor to prevent instantiation
   * Use the class directly as a static reference
   */
  private constructor() {}
}

// Export the class with the reference property on the constructor
// This allows TypeScript to recognize the reference property on the class itself
// Use 'as const' assertion to preserve the literal type of the reference string
/**
 * Action class for actions/setup-node@v4
 *
 * This class represents the imported action and provides type-safe access
 * to the action reference string.
 *
 * This is a static class - use the class directly, no instantiation needed.
 * Example: step.uses(ActionsSetupNode4)
 *
 * @see {@link https://github.com/actions/setup-node GitHub Repository}
 */
export const ActionsSetupNode4 = ActionsSetupNode4Impl as typeof ActionsSetupNode4Impl & {
  readonly reference: "actions/setup-node@v4";
};

// Add reference property to the exported class for runtime access
Object.defineProperty(ActionsSetupNode4, "reference", {
  value: "actions/setup-node@v4",
  writable: false,
  enumerable: true,
  configurable: false,
});
